export const playerSprite = {
  id: 0,
  name: 'Font',
  size: 8,
  colors: {
    1: '#ffffff',
  },
  frames: [
    [
      [ undefined, undefined, undefined, 1, 1, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, 1, 1, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, 1, 1, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, 1, 1, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, 1, 1, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, 1, 1, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
    [
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
      [ undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined ],
    ],
  ]
}
